name: End to End
on: [pull_request]

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run cypress
        run: yarn test:e2e:ci
